package com.rick.db.mybatis.mapper;

import com.rick.db.mybatis.model.SysRolePrivilege;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    List<SysRolePrivilege> selectAll();
}