package com.rick.db.mybatis.mapper;

import com.rick.db.mybatis.model.SysUserRole;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated
     */
    List<SysUserRole> selectAll();
}